[package]
name = "pond_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
handlebars = "6.0.0"
lazy_static = "1.5.0"
regex = "1.10.6"
rocket = "0.5.1"
serde = { version = "1.0.209", features = ["derive"] }
